volumes:
  stormkit:

services:
  db:
    image: postgres
    restart: always
    ports:
      - published: 5432
        target: 5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    container_name: redis
    image: redis:6.2.12
    restart: always
    ports:
      - published: 6379
        target: 6379

  redis-monitoring:
    image: hibiken/asynqmon
    ports:
      - published: 8086
        target: 8086
    environment:
      - PORT=8086
      - REDIS_ADDR=redis:6379

  workerserver:
    image: ghcr.io/stormkit-io/workerserver:latest
    restart: always
    container_name: workerserver
    env_file:
      - .env
    volumes:
      - stormkit:/deployments
    environment:
      - NODE_VERSION=22

  hosting:
    image: ghcr.io/stormkit-io/hosting:latest
    restart: always
    container_name: hosting
    # Needed only when using a FileSys Deployment
    volumes:
      - stormkit:/deployments
    env_file:
      - .env
    environment:
      - NODE_VERSION=22
    ports:
      - published: 80
        target: 80
      - published: 443
        target: 443
